In [160]:
import numpy as np
import pandas as pd
import plotly.express as px
from ydata_profiling import ProfileReport
import scipy.stats as stats

In [161]:
data = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

# EDA

In [162]:
#read all columns
pd.set_option('display.max_columns', None)
data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,NaN,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [163]:
# need to change the type of the MSSubClass from int to object as its categorical data not numeric data

data['MSSubClass'] = data['MSSubClass'].astype(str)

In [164]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   object
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(34), object(44)
memory usage: 924.0+ KB
None

In [165]:
data.describe(include='all')

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
count,1460.000000,1460,1460,1201.000000,1460.000000,1460,91,1460,1460,1460,1460,1460,1460,1460,1460,1460,1460,1460.000000,1460.000000,1460.000000,1460.000000,1460,1460,1460,1460,588,1452.000000,1460,1460,1460,1423,1423,1422,1423,1460.000000,1422,1460.000000,1460.000000,1460.000000,1460,1460,1460,1459,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460,1460.000000,1460,1460.000000,770,1379,1379.000000,1379,1460.000000,1460.000000,1379,1379,1460,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,7,281,54,1460.000000,1460.000000,1460.000000,1460,1460,1460.000000
unique,NaN,15,5,NaN,NaN,2,2,4,4,2,5,3,25,9,8,5,8,NaN,NaN,NaN,NaN,6,8,15,16,3,NaN,4,5,6,4,4,4,6,NaN,6,NaN,NaN,NaN,6,5,2,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,7,NaN,5,6,NaN,3,NaN,NaN,5,5,3,NaN,NaN,NaN,NaN,NaN,NaN,3,4,4,NaN,NaN,NaN,9,6,NaN
top,NaN,20,RL,NaN,NaN,Pave,Grvl,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,1Fam,1Story,NaN,NaN,NaN,NaN,Gable,CompShg,VinylSd,VinylSd,BrkFace,NaN,TA,TA,PConc,TA,TA,No,Unf,NaN,Unf,NaN,NaN,NaN,GasA,Ex,Y,SBrkr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TA,NaN,Typ,NaN,Gd,Attchd,NaN,Unf,NaN,NaN,TA,TA,Y,NaN,NaN,NaN,NaN,NaN,NaN,Gd,MnPrv,Shed,NaN,NaN,NaN,WD,Normal,NaN
freq,NaN,536,1151,NaN,NaN,1454,50,925,1311,1459,1052,1382,225,1260,1445,1220,726,NaN,NaN,NaN,NaN,1141,1434,515,504,445,NaN,906,1282,647,649,1311,953,430,NaN,1256,NaN,NaN,NaN,1428,741,1365,1334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,735,NaN,1360,NaN,380,870,NaN,605,NaN,NaN,1311,1326,1340,NaN,NaN,NaN,NaN,NaN,NaN,3,157,49,NaN,NaN,NaN,1267,1198,NaN
mean,730.500000,NaN,NaN,70.049958,10516.828082,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.099315,5.575342,1971.267808,1984.865753,NaN,NaN,NaN,NaN,NaN,103.685262,NaN,NaN,NaN,NaN,NaN,NaN,NaN,443.639726,NaN,46.549315,567.240411,1057.429452,NaN,NaN,NaN,NaN,1162.626712,346.992466,5.844521,1515.463699,0.425342,0.057534,1.565068,0.382877,2.866438,1.046575,NaN,6.517808,NaN,0.613014,NaN,NaN,1978.506164,NaN,1.767123,472.980137,NaN,NaN,NaN,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,NaN,NaN,NaN,43.489041,6.321918,2007.815753,NaN,NaN,180921.195890
std,421.610009,NaN,NaN,24.284752,9981.264932,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.382997,1.112799,30.202904,20.645407,NaN,NaN,NaN,NaN,NaN,181.066207,NaN,NaN,NaN,NaN,NaN,NaN,NaN,456.098091,NaN,161.319273,441.866955,438.705324,NaN,NaN,NaN,NaN,386.587738,436.528436,48.623081,525.480383,0.518911,0.238753,0.550916,0.502885,0.815778,0.220338,NaN,1.625393,NaN,0.644666,NaN,NaN,24.689725,NaN,0.747315,213.804841,NaN,NaN,NaN,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,NaN,NaN,NaN,496.123024,2.703626,1.328095,NaN,NaN,79442.502883
min,1.000000,NaN,NaN,21.000000,1300.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,1872.000000,1950.000000,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,334.000000,0.000000,0.000000,334.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,2.000000,NaN,0.000000,NaN,NaN,1900.000000,NaN,0.000000,0.000000,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,0.000000,1.000000,2006.000000,NaN,NaN,34900.000000
25%,365.750000,NaN,NaN,59.000000,7553.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,5.000000,1954.000000,1967.000000,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,0.000000,223.000000,795.750000,NaN,NaN,NaN,NaN,882.000000,0.000000,0.000000,1129.500000,0.000000,0.000000,1.000000,0.000000,2.000000,1.000000,NaN,5.000000,NaN,0.000000,NaN,NaN,1961.000000,NaN,1.000000,334.500000,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,0.000000,5.000000,2007.000000,NaN,NaN,129975.000000
50%,730.500000,NaN,NaN,69.000000,9478.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.000000,5.000000,1973.000000,1994.000000,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,383.500000,NaN,0.000000,477.500000,991.500000,NaN,NaN,NaN,NaN,1087.000000,0.000000,0.000000,1464.000000,0.000000,0.000000,2.000000,0.000000,3.000000,1.000000,NaN,6.000000,NaN,1.000000,NaN,NaN,1980.000000,NaN,2.000000,480.000000,NaN,NaN,NaN,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,0.000000,6.000000,2008.000000,NaN,NaN,163000.000000
75%,1095.250000,NaN,NaN,80.000000,11601.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.000000,6.000000,2000.000000,2004.000000,NaN,NaN,NaN,NaN,NaN,166.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,712.250000,NaN,0.000000,808.000000,1298.250000,NaN,NaN,NaN,NaN,1391.250000,728.000000,0.000000,1776.750000,1.000000,0.000000,2.000000,1.000000,3.000000,1.000000,NaN,7.000000,NaN,1.000000,NaN,NaN,2002.000000,NaN,2.000000,576.000000,NaN,NaN,NaN,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,0.000000,8.000000,2009.000000,NaN,NaN,214000.000000
max,1460.000000,NaN,NaN,313.000000,215245.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.000000,9.000000,2010.000000,2010.000000,NaN,NaN,NaN,NaN,NaN,1600.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5644.000000,NaN,1474.000000,2336.000000,6110.000000,NaN,NaN,NaN,NaN,4692.000000,2065.000000,572.000000,5642.000000,3.000000,2.000000,3.000000,2.000000,8.000000,3.000000,NaN,14.000000,NaN,3.000000,NaN,NaN,2010.000000,NaN,4.000000,1418.000000,NaN,NaN,NaN,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,NaN,NaN,NaN,15500.000000,12.000000,2010.000000,NaN,NaN,755000.000000

In [166]:
data["house_Age"]=data["YrSold"]-data["YearBuilt"]

In [167]:
Numi_col= list(set(data.select_dtypes([float,int]).columns))
non_needed_features=["Id",'MoSold','YearRemodAdd','YrSold','YearBuilt',"GarageYrBlt"]
for i in non_needed_features:
    if i in Numi_col:
        Numi_col.remove(i)
print(Numi_col)

['LotArea', '1stFlrSF', 'OverallCond', 'BedroomAbvGr', 'BsmtUnfSF', 'LowQualFinSF', 'GarageCars', 'Fireplaces', '3SsnPorch', 'BsmtHalfBath', 'ScreenPorch', 'PoolArea', '2ndFlrSF', 'EnclosedPorch', 'MasVnrArea', 'TotalBsmtSF', 'WoodDeckSF', 'BsmtFinSF2', 'GarageArea', 'GrLivArea', 'BsmtFinSF1', 'HalfBath', 'house_Age', 'LotFrontage', 'SalePrice', 'KitchenAbvGr', 'BsmtFullBath', 'OverallQual', 'TotRmsAbvGrd', 'OpenPorchSF', 'MiscVal', 'FullBath']

In [168]:
Cati_col = list(set(data.select_dtypes(object)))
print(Cati_col)

['BsmtExposure', 'Functional', 'Heating', 'PavedDrive', 'Electrical', 'SaleType', 'RoofStyle', 'HeatingQC', 'KitchenQual', 'GarageFinish', 'BsmtQual', 'CentralAir', 'BsmtCond', 'Condition2', 'Street', 'BldgType', 'PoolQC', 'MiscFeature', 'LandContour', 'GarageCond', 'Utilities', 'Exterior1st', 'Neighborhood', 'LandSlope', 'GarageQual', 'MasVnrType', 'LotShape', 'Exterior2nd', 'FireplaceQu', 'ExterQual', 'Fence', 'LotConfig', 'HouseStyle', 'Condition1', 'ExterCond', 'SaleCondition', 'GarageType', 'Alley', 'BsmtFinType2', 'Foundation', 'BsmtFinType1', 'RoofMatl', 'MSSubClass', 'MSZoning']

## Report numeric features

In [169]:
# # report Numi_col
# numi_rep = ProfileReport(data[Numi_col], title="Numi_col Report" , minimal=True)

# rep=numi_rep.to_notebook_iframe()
# rep

##### correlation check

In [170]:
corr_matrix= data[Numi_col].corr(method="spearman")
#used Spearman correlation method because the data has outliers

In [171]:
px.imshow(corr_matrix,
                width=1200,height=800,
                color_continuous_scale=px.colors.sequential.RdBu , zmin=-.75,zmax=.75)

In [172]:
#filter correlation matrix
corr_over7 = corr_matrix[(corr_matrix >= 0.7) & (corr_matrix < 1)]

In [173]:
px.imshow(corr_over7,
                width=1200,height=800,
            )

###### now we will drop features that : 
have high correlation with other features over 70%, keep the high correlated with target and drop the another one 
            ['1stFlrSF', 'GarageArea', 'TotRmsAbvGrd' ]

In [174]:
features_to_delete = ['1stFlrSF', 'GarageArea', 'TotRmsAbvGrd' ]
for i in features_to_delete:
    Numi_col.remove(i)

In [175]:
print (len(Numi_col), Numi_col)

29 ['LotArea', 'OverallCond', 'BedroomAbvGr', 'BsmtUnfSF', 'LowQualFinSF', 'GarageCars', 'Fireplaces', '3SsnPorch', 'BsmtHalfBath', 'ScreenPorch', 'PoolArea', '2ndFlrSF', 'EnclosedPorch', 'MasVnrArea', 'TotalBsmtSF', 'WoodDeckSF', 'BsmtFinSF2', 'GrLivArea', 'BsmtFinSF1', 'HalfBath', 'house_Age', 'LotFrontage', 'SalePrice', 'KitchenAbvGr', 'BsmtFullBath', 'OverallQual', 'OpenPorchSF', 'MiscVal', 'FullBath']

#### check for missing values

##### missing values

In [176]:
# check how many rows with missig values from 1460 rows
rows_with_nan = data[Numi_col].isna().any(axis=1).sum()
print(rows_with_nan)
print(f"{rows_with_nan/1460*100:.2f}% of rows with missing values")

265
18.15% of rows with missing values

##### we will impute the missing values in 'LotFrontage' with the Mean of the column as in had 259 missing values most of the nulls 
 then we will drop rest of numeric features with missing values

In [177]:
data['LotFrontage']=data['LotFrontage'].fillna(70)

In [178]:
data.dropna(subset=["MasVnrArea"], inplace=True)

In [179]:
data[Numi_col].info()

<class 'pandas.core.frame.DataFrame'>
Index: 1452 entries, 0 to 1459
Data columns (total 29 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   LotArea        1452 non-null   int64
 1   OverallCond    1452 non-null   int64
 2   BedroomAbvGr   1452 non-null   int64
 3   BsmtUnfSF      1452 non-null   int64
 4   LowQualFinSF   1452 non-null   int64
 5   GarageCars     1452 non-null   int64
 6   Fireplaces     1452 non-null   int64
 7   3SsnPorch      1452 non-null   int64
 8   BsmtHalfBath   1452 non-null   int64
 9   ScreenPorch    1452 non-null   int64
 10  PoolArea       1452 non-null   int64
 11  2ndFlrSF       1452 non-null   int64
 12  EnclosedPorch  1452 non-null   int64
 13  MasVnrArea     1452 non-null   float64
 14  TotalBsmtSF    1452 non-null   int64
 15  WoodDeckSF     1452 non-null   int64
 16  BsmtFinSF2     1452 non-null   int64
 17  GrLivArea      1452 non-null   int64
 18  BsmtFinSF1     1452 non-null   int64
 19  HalfBath       1452 non-null   int64
 20  house_Age      1452 non-null   int64
 21  LotFrontage    1452 non-null   float64
 22  SalePrice      1452 non-null   int64
 23  KitchenAbvGr   1452 non-null   int64
 24  BsmtFullBath   1452 non-null   int64
 25  OverallQual    1452 non-null   int64
 26  OpenPorchSF    1452 non-null   int64
 27  MiscVal        1452 non-null   int64
 28  FullBath       1452 non-null   int64
dtypes: float64(2), int64(27)
memory usage: 340.3 KB

#### outliers

In [180]:
small_scale = ['WoodDeckSF', 'LowQualFinSF', 'BsmtUnfSF', 'BsmtHalfBath', 'HalfBath', 'KitchenAbvGr',  'BsmtFullBath', 'BsmtFinSF1', '2ndFlrSF', 'FullBath', 'GarageCars', 'PoolArea', 'OpenPorchSF', 'GrLivArea', 'BedroomAbvGr', 'MasVnrArea', 'OverallQual', '3SsnPorch', 'house_Age', 'TotalBsmtSF', 'ScreenPorch', 'LotFrontage', 'BsmtFinSF2', 'Fireplaces', 'EnclosedPorch', 'MiscVal', 'OverallCond']
large_scale=['SalePrice', 'LotArea']
 
graphoutliers = px.box(data[small_scale], orientation= 'h' , height= 800) 
graphoutliers.show()

In [181]:
graphoutliers2 = px.box(data[large_scale], orientation='h' )
graphoutliers2.show()

### now we can say we have 29 Numerical Features ready to enter the Pipeline phase

## report catagorical features

In [182]:
# #cati_col
# cati_rep = ProfileReport(data[Cati_col], title="Cati_col Report" ,minimal=True)

# rep2= cati_rep.to_notebook_iframe()
# rep2

In [183]:
data[Cati_col].describe()

,BsmtExposure,Functional,Heating,PavedDrive,Electrical,SaleType,RoofStyle,HeatingQC,KitchenQual,GarageFinish,BsmtQual,CentralAir,BsmtCond,Condition2,Street,BldgType,PoolQC,MiscFeature,LandContour,GarageCond,Utilities,Exterior1st,Neighborhood,LandSlope,GarageQual,MasVnrType,LotShape,Exterior2nd,FireplaceQu,ExterQual,Fence,LotConfig,HouseStyle,Condition1,ExterCond,SaleCondition,GarageType,Alley,BsmtFinType2,Foundation,BsmtFinType1,RoofMatl,MSSubClass,MSZoning
count,1414,1452,1452,1452,1451,1452,1452,1452,1452,1371,1415,1452,1415,1452,1452,1452,7,54,1452,1371,1452,1452,1452,1452,1371,588,1452,1452,766,1452,281,1452,1452,1452,1452,1452,1371,90,1414,1452,1415,1452,1452,1452
unique,4,7,6,3,5,9,6,5,4,3,4,2,4,8,2,5,3,4,4,5,2,15,25,3,5,3,4,16,5,4,4,5,8,9,5,6,6,2,6,6,6,8,15,5
top,No,Typ,GasA,Y,SBrkr,WD,Gable,Ex,TA,Unf,TA,Y,TA,Norm,Pave,1Fam,Gd,Shed,Lvl,TA,AllPub,VinylSd,NAmes,Gtl,TA,BrkFace,Reg,VinylSd,Gd,TA,MnPrv,Inside,1Story,Norm,TA,Normal,Attchd,Grvl,Unf,PConc,Unf,CompShg,20,RL
freq,946,1353,1420,1332,1326,1262,1134,734,734,605,648,1357,1304,1437,1446,1213,3,49,1303,1318,1451,510,225,1374,1303,445,919,499,378,906,157,1046,721,1252,1274,1194,863,50,1248,639,428,1426,532,1146

##### split the catagorical features into nominal and ordinal

#### nominal feature

In [184]:
nominal_features = [
    'MSSubClass',
    'MSZoning',
    'Street',
    'Alley',
    'LandContour',
    'Utilities',
    'LotConfig',
    'Neighborhood',
    'Condition1',
    'Condition2',
    'BldgType',
    'HouseStyle',
    'RoofStyle',
    'RoofMatl',
    'Exterior1st',
    'Exterior2nd',
    'MasVnrType',
    'Foundation',
    'Heating',
    'CentralAir',
    'GarageType',
    'MiscFeature',
    'SaleType',
    'SaleCondition'
]

In [185]:
ordinal_features = [
    'LotShape',
    'LandSlope',
    'ExterQual',
    'ExterCond',
    'BsmtQual',
    'BsmtCond',
    'BsmtExposure',
    'BsmtFinType1',
    'BsmtFinType2',
    'HeatingQC',
    'Electrical',
    'KitchenQual',
    'Functional',
    'FireplaceQu',
    'GarageFinish',
    'GarageQual',
    'GarageCond',
    'PavedDrive',
    'PoolQC',
    'Fence'
]

##### I will make histograms for nominal_features to check the distribution of features, and drop the features that have 1 unique value replicated more then 99%

In [186]:

for i in nominal_features:
    fig = px.histogram(data_frame=data,
             x=i,
             histfunc='avg', # This is the important part
             title=f'Average Sale Price by {i}')
    #fig.show()

##### so ['Condition2', 'Street', 'Alley', 'Utilities'] are non usable

##### also in another way  I can say all features affect price so i will encode into sub-features ,to use ANOVA F-value correlation test then check for features that didnt do any correlation with price

In [187]:
from sklearn.feature_selection import f_regression
from sklearn.preprocessing import OneHotEncoder # or i will use pandas.get_dummies() easier.

In [188]:
sub_features = pd.get_dummies(data[nominal_features], drop_first=True)

In [189]:
X = sub_features
y = data['SalePrice']
f_statistic, p_values = f_regression(X, y)

sub_features_test = pd.DataFrame({
    'Feature': X.columns,
    'F-Statistic': f_statistic,
    'p-value': p_values
})

sub_features_test

                   Feature  F-Statistic       p-value
0           MSSubClass_160    18.676942  1.653934e-05
1           MSSubClass_180     9.884508  1.700558e-03
2           MSSubClass_190    12.778541  3.621182e-04
3            MSSubClass_20     2.205227  1.377610e-01
4            MSSubClass_30    87.796780  2.680091e-20
..                     ...          ...           ...
148  SaleCondition_AdjLand     3.740240  5.331120e-02
149   SaleCondition_Alloca     0.466006  4.949392e-01
150   SaleCondition_Family     3.107716  7.813278e-02
151   SaleCondition_Normal    33.458179  8.905472e-09
152  SaleCondition_Partial   201.608849  6.093061e-43

[153 rows x 3 columns]

###### make a list sub_features with P-value < 0.05 (the features that are significant) then check what features are not in this list

In [190]:
Fnames= list(sub_features_test["Feature"][sub_features_test["p-value"]<0.05])  # sub_features with P-value < 0.05

cleaned = [f.split("_")[0] for f in Fnames]  # Remove the suffix from the feature names to convert it into the real features names 

unique_features = sorted(set(cleaned))

print(unique_features)
print(nominal_features)

['BldgType', 'CentralAir', 'Condition1', 'Exterior1st', 'Exterior2nd', 'Foundation', 'GarageType', 'Heating', 'HouseStyle', 'LandContour', 'LotConfig', 'MSSubClass', 'MSZoning', 'MasVnrType', 'MiscFeature', 'Neighborhood', 'RoofMatl', 'RoofStyle', 'SaleCondition', 'SaleType']
['MSSubClass', 'MSZoning', 'Street', 'Alley', 'LandContour', 'Utilities', 'LotConfig', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'Foundation', 'Heating', 'CentralAir', 'GarageType', 'MiscFeature', 'SaleType', 'SaleCondition']

In [191]:
diff = list(set(unique_features) ^ set(nominal_features))
print("Different elements:", diff)

Different elements: ['Condition2', 'Street', 'Utilities', 'Alley']

In [192]:
px.histogram(data[['Alley', 'Condition2', 'Street', 'Utilities']])

In [193]:
for i in ['Alley', 'Condition2', 'Street', 'Utilities']:
    
    nominal_features.remove(i)
print(len(nominal_features), nominal_features)

20 ['MSSubClass', 'MSZoning', 'LandContour', 'LotConfig', 'Neighborhood', 'Condition1', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'Foundation', 'Heating', 'CentralAir', 'GarageType', 'MiscFeature', 'SaleType', 'SaleCondition']

##### that proved the 1st solution

##### check for null values

In [194]:
data[nominal_features].isna().sum()[lambda x: x > 0]

MasVnrType      864
GarageType       81
MiscFeature    1398
dtype: int64

In [195]:
# replace nulls with 0
cols_to_fill_none = ['MasVnrType', 'GarageType', 'MiscFeature']

data[cols_to_fill_none] = data[cols_to_fill_none].fillna('None')

In [196]:
data[nominal_features].describe()

,MSSubClass,MSZoning,LandContour,LotConfig,Neighborhood,Condition1,BldgType,HouseStyle,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,Foundation,Heating,CentralAir,GarageType,MiscFeature,SaleType,SaleCondition
count,1452,1452,1452,1452,1452,1452,1452,1452,1452,1452,1452,1452,1452,1452,1452,1452,1452,1452,1452,1452
unique,15,5,4,5,25,9,5,8,6,8,15,16,4,6,6,2,7,5,9,6
top,20,RL,Lvl,Inside,NAmes,Norm,1Fam,1Story,Gable,CompShg,VinylSd,VinylSd,None,PConc,GasA,Y,Attchd,None,WD,Normal
freq,532,1146,1303,1046,225,1252,1213,721,1134,1426,510,499,864,639,1420,1357,863,1398,1262,1194

##### Cardinality is ok

#### ordinal features

##### check nulls

In [197]:
data[ordinal_features].describe()

,LotShape,LandSlope,ExterQual,ExterCond,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,HeatingQC,Electrical,KitchenQual,Functional,FireplaceQu,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence
count,1452,1452,1452,1452,1415,1415,1414,1415,1414,1452,1451,1452,1452,766,1371,1371,1371,1452,7,281
unique,4,3,4,5,4,4,4,6,6,5,5,4,7,5,3,5,5,3,3,4
top,Reg,Gtl,TA,TA,TA,TA,No,Unf,Unf,Ex,SBrkr,TA,Typ,Gd,Unf,TA,TA,Y,Gd,MnPrv
freq,919,1374,906,1274,648,1304,946,428,1248,734,1326,734,1353,378,605,1303,1318,1332,3,157

In [198]:
data[ordinal_features].isna().sum()[lambda x: x > 0]

BsmtQual          37
BsmtCond          37
BsmtExposure      38
BsmtFinType1      37
BsmtFinType2      38
Electrical         1
FireplaceQu      686
GarageFinish      81
GarageQual        81
GarageCond        81
PoolQC          1445
Fence           1171
dtype: int64

##### no correlated features with nulls between Nominal & Ordinal data , except garage and its 81 feature the same so no missing entry data , will use np.non while encoding

##### now I will make the Maps needed for Ordinal encoding

In [199]:
for i in ordinal_features:
    L= (list(data[i].unique()))
    print(str(i)+" : "+str(L))

LotShape : ['Reg', 'IR1', 'IR2', 'IR3']
LandSlope : ['Gtl', 'Mod', 'Sev']
ExterQual : ['Gd', 'TA', 'Ex', 'Fa']
ExterCond : ['TA', 'Gd', 'Fa', 'Po', 'Ex']
BsmtQual : ['Gd', 'TA', 'Ex', nan, 'Fa']
BsmtCond : ['TA', 'Gd', nan, 'Fa', 'Po']
BsmtExposure : ['No', 'Gd', 'Mn', 'Av', nan]
BsmtFinType1 : ['GLQ', 'ALQ', 'Unf', 'Rec', 'BLQ', nan, 'LwQ']
BsmtFinType2 : ['Unf', 'BLQ', nan, 'ALQ', 'Rec', 'LwQ', 'GLQ']
HeatingQC : ['Ex', 'Gd', 'TA', 'Fa', 'Po']
Electrical : ['SBrkr', 'FuseF', 'FuseA', 'FuseP', 'Mix', nan]
KitchenQual : ['Gd', 'TA', 'Ex', 'Fa']
Functional : ['Typ', 'Min1', 'Maj1', 'Min2', 'Mod', 'Maj2', 'Sev']
FireplaceQu : [nan, 'TA', 'Gd', 'Fa', 'Ex', 'Po']
GarageFinish : ['RFn', 'Unf', 'Fin', nan]
GarageQual : ['TA', 'Fa', 'Gd', nan, 'Ex', 'Po']
GarageCond : ['TA', 'Fa', nan, 'Gd', 'Po', 'Ex']
PavedDrive : ['Y', 'N', 'P']
PoolQC : [nan, 'Ex', 'Fa', 'Gd']
Fence : [nan, 'MnPrv', 'GdWo', 'GdPrv', 'MnWw']

In [200]:
# maps of ordinal encoding

# 5-Level Quality/Condition Scale ('Poor' to 'Excellent')
quality_map_5_levels = {
    'Po': 1, 
    'Fa': 2, 
    'TA': 3, 
    'Gd': 4, 
    'Ex': 5, 
    'Nane':0,
    'nan': 0,
    np.nan: 0,
}


# Basement Finish Scale ('Unfinished' to 'Good Living Quarters')
bsmt_fin_map = {
    'Unf': 1, 
    'LwQ': 2, 
    'Rec': 3, 
    'BLQ': 4, 
    'ALQ': 5, 
    'GLQ': 6, 
    'Nane':0,
    'nan': 0,
    np.nan: 0,
}


# ## Unique Individual Maps ##

lot_shape_map = {'Reg': 3, 'IR1': 2, 'IR2': 1, 'IR3': 0}

land_slope_map = {'Gtl': 0, 'Mod': 1, 'Sev': 2}

bsmt_cond_map = {'Po': 1, 'Fa': 2, 'TA': 3, 'Gd': 4, 'Nane': 0,  'nan': 0, np.nan: 0}

bsmt_exposure_map = {'No': 1, 'Mn': 2, 'Av': 3, 'Gd': 4, 'Nane': 0, 'nan': 0, np.nan: 0}

garage_finish_map = {'Unf': 1, 'RFn': 2, 'Fin': 3, 'Nane': 0, 'nan': 0, np.nan: 0}

paved_drive_map = {'N': 0, 'P': 1, 'Y': 2}

##### lets try the encoding

In [201]:
encodata = pd.DataFrame()

# Apply the common 5-Level Quality Map
encodata['ExterQual'] = data['ExterQual'].replace(quality_map_5_levels)
encodata['ExterCond'] = data['ExterCond'].replace(quality_map_5_levels)
encodata['BsmtQual'] = data['BsmtQual'].replace(quality_map_5_levels)
encodata['BsmtCond'] = data['BsmtCond'].replace(quality_map_5_levels)
encodata['HeatingQC'] = data['HeatingQC'].replace(quality_map_5_levels)
encodata['KitchenQual'] = data['KitchenQual'].replace(quality_map_5_levels)
encodata['FireplaceQu'] = data['FireplaceQu'].replace(quality_map_5_levels)
encodata['GarageQual'] = data['GarageQual'].replace(quality_map_5_levels)
encodata['GarageCond'] = data['GarageCond'].replace(quality_map_5_levels)
encodata['PoolQC'] = data['PoolQC'].replace(quality_map_5_levels)

# Apply the Basement Finish Map
encodata['BsmtFinType1'] = data['BsmtFinType1'].replace(bsmt_fin_map)
encodata['BsmtFinType2'] = data['BsmtFinType2'].replace(bsmt_fin_map)

# Apply the Unique/Individual Maps
encodata['LotShape'] = data['LotShape'].replace(lot_shape_map)
encodata['LandSlope'] = data['LandSlope'].replace(land_slope_map)
encodata['BsmtExposure'] = data['BsmtExposure'].replace(bsmt_exposure_map)
encodata['GarageFinish'] = data['GarageFinish'].replace(garage_finish_map)
encodata['PavedDrive'] = data['PavedDrive'].replace(paved_drive_map)

C:\Users\DUBAI STORE\AppData\Local\Temp\ipykernel_13296\4280008007.py:4: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

C:\Users\DUBAI STORE\AppData\Local\Temp\ipykernel_13296\4280008007.py:5: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

C:\Users\DUBAI STORE\AppData\Local\Temp\ipykernel_13296\4280008007.py:6: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

C:\Users\DUBAI STORE\AppData\Local\Temp\ipykernel_13296\4280008007.py:7: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

C:\Users\DUBAI STORE\AppData\Local\Temp\ipykernel_13296\4280008007.py:8: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

C:\Users\DUBAI STORE\AppData\Local\Temp\ipykernel_13296\4280008007.py:9: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

C:\Users\DUBAI STORE\AppData\Local\Temp\ipykernel_13296\4280008007.py:10: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

C:\Users\DUBAI STORE\AppData\Local\Temp\ipykernel_13296\4280008007.py:11: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

C:\Users\DUBAI STORE\AppData\Local\Temp\ipykernel_13296\4280008007.py:12: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

C:\Users\DUBAI STORE\AppData\Local\Temp\ipykernel_13296\4280008007.py:13: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

C:\Users\DUBAI STORE\AppData\Local\Temp\ipykernel_13296\4280008007.py:16: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

C:\Users\DUBAI STORE\AppData\Local\Temp\ipykernel_13296\4280008007.py:17: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

C:\Users\DUBAI STORE\AppData\Local\Temp\ipykernel_13296\4280008007.py:20: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

C:\Users\DUBAI STORE\AppData\Local\Temp\ipykernel_13296\4280008007.py:21: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

C:\Users\DUBAI STORE\AppData\Local\Temp\ipykernel_13296\4280008007.py:22: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

C:\Users\DUBAI STORE\AppData\Local\Temp\ipykernel_13296\4280008007.py:23: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

C:\Users\DUBAI STORE\AppData\Local\Temp\ipykernel_13296\4280008007.py:24: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

In [202]:
encodata.head()

,ExterQual,ExterCond,BsmtQual,BsmtCond,HeatingQC,KitchenQual,FireplaceQu,GarageQual,GarageCond,PoolQC,BsmtFinType1,BsmtFinType2,LotShape,LandSlope,BsmtExposure,GarageFinish,PavedDrive
0,4,3,4.0,3.0,5,4,0.0,3.0,3.0,0.0,6.0,1.0,3,0,1.0,2.0,2
1,3,3,4.0,3.0,5,3,3.0,3.0,3.0,0.0,5.0,1.0,3,0,4.0,2.0,2
2,4,3,4.0,3.0,5,4,3.0,3.0,3.0,0.0,6.0,1.0,2,0,2.0,2.0,2
3,3,3,3.0,4.0,4,4,4.0,3.0,3.0,0.0,5.0,1.0,2,0,1.0,1.0,2
4,4,3,4.0,3.0,5,4,3.0,3.0,3.0,0.0,6.0,1.0,2,0,3.0,2.0,2

In [203]:
C = list(encodata.columns)
for i in C:
    blot=px.box(
        encodata,
        y=data['SalePrice'],
        x=i,
        title=f'Box Plot of {i}'
    )
    #blot.show()

##### check some correlation

In [204]:
encodata['SalePrice']= data['SalePrice']
corre2=encodata.corr()
px.imshow(corre2,
                width=1200,height=800,
                color_continuous_scale=px.colors.sequential.RdBu , zmin=-1,zmax=1)

In [205]:
#no need for GarageCond as very correlated with GarageQual 96% correlation
ordinal_features.remove("GarageCond")

# and finaly the PHASE ONE (EDA) & Features selection ended

In [206]:
print('Numerical features:', len(Numi_col), Numi_col, 
      '\n\n\nNominal features:', len(nominal_features), nominal_features, 
      '\n\n\nOrdinal features:', len(ordinal_features), ordinal_features)

Numerical features: 29 ['LotArea', 'OverallCond', 'BedroomAbvGr', 'BsmtUnfSF', 'LowQualFinSF', 'GarageCars', 'Fireplaces', '3SsnPorch', 'BsmtHalfBath', 'ScreenPorch', 'PoolArea', '2ndFlrSF', 'EnclosedPorch', 'MasVnrArea', 'TotalBsmtSF', 'WoodDeckSF', 'BsmtFinSF2', 'GrLivArea', 'BsmtFinSF1', 'HalfBath', 'house_Age', 'LotFrontage', 'SalePrice', 'KitchenAbvGr', 'BsmtFullBath', 'OverallQual', 'OpenPorchSF', 'MiscVal', 'FullBath']


Nominal features: 20 ['MSSubClass', 'MSZoning', 'LandContour', 'LotConfig', 'Neighborhood', 'Condition1', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'Foundation', 'Heating', 'CentralAir', 'GarageType', 'MiscFeature', 'SaleType', 'SaleCondition']


Ordinal features: 19 ['LotShape', 'LandSlope', 'ExterQual', 'ExterCond', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'HeatingQC', 'Electrical', 'KitchenQual', 'Functional', 'FireplaceQu', 'GarageFinish', 'GarageQual', 'PavedDrive', 'PoolQC', 'Fence']

In [207]:
# now raise the working data entring Pipeline Phase  XY_Data
XY_data = Numi_col + nominal_features + ordinal_features
XY_Data = pd.DataFrame(data[XY_data])
XY_Data.head()

,LotArea,OverallCond,BedroomAbvGr,BsmtUnfSF,LowQualFinSF,GarageCars,Fireplaces,3SsnPorch,BsmtHalfBath,ScreenPorch,PoolArea,2ndFlrSF,EnclosedPorch,MasVnrArea,TotalBsmtSF,WoodDeckSF,BsmtFinSF2,GrLivArea,BsmtFinSF1,HalfBath,house_Age,LotFrontage,SalePrice,KitchenAbvGr,BsmtFullBath,OverallQual,OpenPorchSF,MiscVal,FullBath,MSSubClass,MSZoning,LandContour,LotConfig,Neighborhood,Condition1,BldgType,HouseStyle,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,Foundation,Heating,CentralAir,GarageType,MiscFeature,SaleType,SaleCondition,LotShape,LandSlope,ExterQual,ExterCond,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,HeatingQC,Electrical,KitchenQual,Functional,FireplaceQu,GarageFinish,GarageQual,PavedDrive,PoolQC,Fence
0,8450,5,3,150,0,2,0,0,0,0,0,854,0,196.0,856,0,0,1710,706,1,5,65.0,208500,1,1,7,61,0,2,60,RL,Lvl,Inside,CollgCr,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,BrkFace,PConc,GasA,Y,Attchd,None,WD,Normal,Reg,Gtl,Gd,TA,Gd,TA,No,GLQ,Unf,Ex,SBrkr,Gd,Typ,NaN,RFn,TA,Y,NaN,NaN
1,9600,8,3,284,0,2,1,0,1,0,0,0,0,0.0,1262,298,0,1262,978,0,31,80.0,181500,1,0,6,0,0,2,20,RL,Lvl,FR2,Veenker,Feedr,1Fam,1Story,Gable,CompShg,MetalSd,MetalSd,None,CBlock,GasA,Y,Attchd,None,WD,Normal,Reg,Gtl,TA,TA,Gd,TA,Gd,ALQ,Unf,Ex,SBrkr,TA,Typ,TA,RFn,TA,Y,NaN,NaN
2,11250,5,3,434,0,2,1,0,0,0,0,866,0,162.0,920,0,0,1786,486,1,7,68.0,223500,1,1,7,42,0,2,60,RL,Lvl,Inside,CollgCr,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,BrkFace,PConc,GasA,Y,Attchd,None,WD,Normal,IR1,Gtl,Gd,TA,Gd,TA,Mn,GLQ,Unf,Ex,SBrkr,Gd,Typ,TA,RFn,TA,Y,NaN,NaN
3,9550,5,3,540,0,3,1,0,0,0,0,756,272,0.0,756,0,0,1717,216,0,91,60.0,140000,1,1,7,35,0,1,70,RL,Lvl,Corner,Crawfor,Norm,1Fam,2Story,Gable,CompShg,Wd Sdng,Wd Shng,None,BrkTil,GasA,Y,Detchd,None,WD,Abnorml,IR1,Gtl,TA,TA,TA,Gd,No,ALQ,Unf,Gd,SBrkr,Gd,Typ,Gd,Unf,TA,Y,NaN,NaN
4,14260,5,4,490,0,3,1,0,0,0,0,1053,0,350.0,1145,192,0,2198,655,1,8,84.0,250000,1,1,8,84,0,2,60,RL,Lvl,FR2,NoRidge,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,BrkFace,PConc,GasA,Y,Attchd,None,WD,Normal,IR1,Gtl,Gd,TA,Gd,TA,Av,GLQ,Unf,Ex,SBrkr,Gd,Typ,TA,RFn,TA,Y,NaN,NaN

In [208]:
XY_Data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1452 entries, 0 to 1459
Data columns (total 68 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   LotArea        1452 non-null   int64
 1   OverallCond    1452 non-null   int64
 2   BedroomAbvGr   1452 non-null   int64
 3   BsmtUnfSF      1452 non-null   int64
 4   LowQualFinSF   1452 non-null   int64
 5   GarageCars     1452 non-null   int64
 6   Fireplaces     1452 non-null   int64
 7   3SsnPorch      1452 non-null   int64
 8   BsmtHalfBath   1452 non-null   int64
 9   ScreenPorch    1452 non-null   int64
 10  PoolArea       1452 non-null   int64
 11  2ndFlrSF       1452 non-null   int64
 12  EnclosedPorch  1452 non-null   int64
 13  MasVnrArea     1452 non-null   float64
 14  TotalBsmtSF    1452 non-null   int64
 15  WoodDeckSF     1452 non-null   int64
 16  BsmtFinSF2     1452 non-null   int64
 17  GrLivArea      1452 non-null   int64
 18  BsmtFinSF1     1452 non-null   int64
 19  HalfBath       1452 non-null   int64
 20  house_Age      1452 non-null   int64
 21  LotFrontage    1452 non-null   float64
 22  SalePrice      1452 non-null   int64
 23  KitchenAbvGr   1452 non-null   int64
 24  BsmtFullBath   1452 non-null   int64
 25  OverallQual    1452 non-null   int64
 26  OpenPorchSF    1452 non-null   int64
 27  MiscVal        1452 non-null   int64
 28  FullBath       1452 non-null   int64
 29  MSSubClass     1452 non-null   object
 30  MSZoning       1452 non-null   object
 31  LandContour    1452 non-null   object
 32  LotConfig      1452 non-null   object
 33  Neighborhood   1452 non-null   object
 34  Condition1     1452 non-null   object
 35  BldgType       1452 non-null   object
 36  HouseStyle     1452 non-null   object
 37  RoofStyle      1452 non-null   object
 38  RoofMatl       1452 non-null   object
 39  Exterior1st    1452 non-null   object
 40  Exterior2nd    1452 non-null   object
 41  MasVnrType     1452 non-null   object
 42  Foundation     1452 non-null   object
 43  Heating        1452 non-null   object
 44  CentralAir     1452 non-null   object
 45  GarageType     1452 non-null   object
 46  MiscFeature    1452 non-null   object
 47  SaleType       1452 non-null   object
 48  SaleCondition  1452 non-null   object
 49  LotShape       1452 non-null   object
 50  LandSlope      1452 non-null   object
 51  ExterQual      1452 non-null   object
 52  ExterCond      1452 non-null   object
 53  BsmtQual       1415 non-null   object
 54  BsmtCond       1415 non-null   object
 55  BsmtExposure   1414 non-null   object
 56  BsmtFinType1   1415 non-null   object
 57  BsmtFinType2   1414 non-null   object
 58  HeatingQC      1452 non-null   object
 59  Electrical     1451 non-null   object
 60  KitchenQual    1452 non-null   object
 61  Functional     1452 non-null   object
 62  FireplaceQu    766 non-null    object
 63  GarageFinish   1371 non-null   object
 64  GarageQual     1371 non-null   object
 65  PavedDrive     1452 non-null   object
 66  PoolQC         7 non-null      object
 67  Fence          281 non-null    object
dtypes: float64(2), int64(27), object(39)
memory usage: 782.7+ KB